export const productList = [
  {
    id: 1,
    name: "粉晶（Rose Quartz）",
    rating: 4.8,
    ingredients: ["愛與療癒能量", "平衡情緒", "促進自我接納"],
    price: 680,
  },
  {
    id: 2,
    name: "紫水晶（Amethyst）",
    rating: 4.9,
    ingredients: ["靜心安神", "增強直覺力", "改善睡眠品質"],
    price: 850,
  },
  {
    id: 3,
    name: "黑曜石（Obsidian）",
    rating: 4.7,
    ingredients: ["吸收負能量", "增強保護力", "幫助釋放壓力"],
    price: 720,
  },
  {
    id: 4,
    name: "白水晶（Clear Quartz）",
    rating: 5.0,
    ingredients: ["能量放大", "淨化空間", "提升專注力"],
    price: 600,
  },
  {
    id: 5,
    name: "綠東陵石（Green Aventurine）",
    rating: 4.5,
    ingredients: ["吸引幸運", "穩定心緒", "促進財運"],
    price: 550,
  },
  {
    id: 6,
    name: "虎眼石（Tiger’s Eye）",
    rating: 4.6,
    ingredients: ["增強自信", "防止猶豫", "帶來勇氣與行動力"],
    price: 750,
  },
  {
    id: 7,
    name: "青金石（Lapis Lazuli）",
    rating: 4.8,
    ingredients: ["促進誠實溝通", "啟發智慧", "提升專注力"],
    price: 980,
  },
  {
    id: 8,
    name: "紅瑪瑙（Red Agate）",
    rating: 4.4,
    ingredients: ["增強生命力", "激發熱情", "帶來勇氣與穩定"],
    price: 620,
  },
  {
    id: 9,
    name: "海藍寶（Aquamarine）",
    rating: 4.9,
    ingredients: ["平衡情緒", "增進表達力", "帶來內在平靜"],
    price: 880,
  },
  {
    id: 10,
    name: "黃水晶（Citrine）",
    rating: 4.7,
    ingredients: ["吸引財富", "促進自信", "帶來樂觀能量"],
    price: 730,
  },
  {
    id: 11,
    name: "月光石（Moonstone）",
    rating: 4.8,
    ingredients: ["提升直覺", "柔化情緒", "助眠與心靈療癒"],
    price: 960,
  },
  {
    id: 12,
    name: "黑碧璽（Black Tourmaline）",
    rating: 4.9,
    ingredients: ["強力防護能量", "吸收負面磁場", "穩定根基"],
    price: 820,
  },
  {
    id: 13,
    name: "紫鋰輝石（Lepidolite）",
    rating: 4.6,
    ingredients: ["釋放焦慮", "帶來平靜", "提升正念"],
    price: 910,
  },
  {
    id: 14,
    name: "琥珀（Amber）",
    rating: 4.5,
    ingredients: ["轉化負能量", "促進健康", "喚起喜悅感"],
    price: 690,
  },
  {
    id: 15,
    name: "黑髮晶（Tourmalinated Quartz）",
    rating: 4.7,
    ingredients: ["防小人", "清除能量阻塞", "增強行動力"],
    price: 770,
  },
];
